# This is a .comp file for limiting max number of arg 
PENALTY_DEFINITION
TYPE ARG                    #We're counting this aa
FRACTION 0.075			    #max  (about two per chain in a 4.5 hept 4HB)
DELTA_START -1
DELTA_END 1
PENALTIES 0 0 50           #These are the penalties for having 1 less alanine than desired, the desired number, and one more alanine than desired.
BEFORE_FUNCTION CONSTANT    #If we have less than 1 fewer alanines than desired, the penalties remain constant (at zero).
AFTER_FUNCTION QUADRATIC    #If we have more than 1 more alanine than desired, the penalties ramp up quadratically.
END_PENALTY_DEFINITION